name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install edge-tts==1.6.2
          pip install -r requirements.txt
      - name: Lint and Test
        run: |
          ruff check .
          pytest -q
